"""Artifacts / MinIO page — S3-compatible artifact store and manifest viewer."""

from __future__ import annotations

import json

import streamlit as st

from chatbot.components import page_proves
from chatbot.config import MINIO_URL
from chatbot.pages._shared import ARTIFACT_MANIFEST, MINIO_BUCKETS


def page_artifacts() -> None:
    st.title("Artifacts / MinIO")
    page_proves(
        "The artifact/blob story — S3-compatible MinIO for models, eval reports, snapshots."
    )
    st.caption(
        "MinIO is the S3-compatible artifact store. Eval reports, retrieval snapshots, and model artifacts are uploaded here."
    )

    col1, col2 = st.columns([2, 1])
    col1.metric("MinIO console", MINIO_URL)
    col2.markdown(f"[Open MinIO]({MINIO_URL})")

    st.subheader("Expected buckets")
    for bucket in MINIO_BUCKETS:
        st.markdown(f"- `{bucket}`")

    st.subheader("What MinIO stores")
    st.markdown(
        "| Bucket | Contents |\n"
        "|---|---|\n"
        "| `handyman-artifacts` | Classifier model artifacts, eval reports, training summaries |\n"
        "| `handyman-evals` | RAG retrieval snapshots, golden eval outputs, RAGAS reports |"
    )

    st.divider()

    st.subheader("Artifact manifest")
    if ARTIFACT_MANIFEST.exists():
        try:
            manifest = json.loads(ARTIFACT_MANIFEST.read_text())
            st.success(f"Loaded `{ARTIFACT_MANIFEST}` — {len(manifest)} entries")
            with st.expander("View manifest"):
                st.json(manifest)
        except Exception as exc:  # noqa: BLE001
            st.warning(f"Could not parse manifest: {exc}")
    else:
        st.info(
            f"`{ARTIFACT_MANIFEST}` is not present in the running container. "
            "This file is a repo-side artifact generated by `scripts/audit_reports.py`. "
            "It is not packaged into the Docker image. "
            "To view it: run `python scripts/audit_reports.py` locally, "
            "then open the generated `reports/artifact_manifest.json`."
        )

    st.divider()

    st.subheader("Default credentials (local dev)")
    st.caption("These match the docker-compose.yml defaults. Change for production.")
    st.code(
        "MINIO_ROOT_USER=minioadmin\nMINIO_ROOT_PASSWORD=minioadmin",
        language="bash",
    )
