FROM python:3.11-slim

# httpx is required by chatbot/api_client.py for all API calls.
RUN pip install --no-cache-dir streamlit httpx

WORKDIR /app

# Required so `from chatbot.api_client import ...` resolves when streamlit
# runs chatbot/main.py as a script — streamlit does not add WORKDIR to sys.path.
ENV PYTHONPATH=/app

COPY chatbot/ ./chatbot/

# Streamlit reads .streamlit/config.toml from the working dir (/app) — ship the theme.
COPY .streamlit/ ./.streamlit/

# Selected non-secret eval reports for the Evaluation Defense page (read-only).
# Generated by the eval pipelines before build; re-included via .dockerignore.
COPY reports/rag/api_eval_report.json ./reports/rag/api_eval_report.json
COPY reports/rag/generation_eval_report.json ./reports/rag/generation_eval_report.json
COPY reports/classification_eval_report.json ./reports/classification_eval_report.json

EXPOSE 8501

CMD ["streamlit", "run", "chatbot/main.py", "--server.port=8501", "--server.address=0.0.0.0"]
